spring.application.name=projekt-order-service
server.port=7500
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
product-service.base-url=${PRODUCT_SERVICE_BASE_URL:http://localhost:8081}
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}
rabbitmq.queue.email=email-queue
auth-server.base-url=${AUTH_SERVER_BASE_URL:http://localhost:8080}